### PR TITLE
fixed ida pro 7 beta6(170831) x86 crash and code refactor

### PR DESCRIPTION
**Pull request by fjh658**
1. fixed ida pro 7 beta6 x86 crash. idainfo object has no attribute 'procname'
image

image

ida pro 7 beta6 x86,  The idainfo object has still procName api

2. refactor: removed "from idc_bc695" According to hexray log document, idc has been done on the adapter idc_bc695, do not need to expose idc_bc695.
```ini
// python.cfg 
// Should the plugin automatically load a 6.95 bw-compatibility layer?
AUTOIMPORT_COMPAT_IDA695 = YES
```
```python
# idc.py
# Compatibility macros (auto-generated part. Comes first so
# that any re-definition below will override auto-generated part)
if sys.modules["__main__"].IDAPYTHON_COMPAT_695_API:
    # ...
    from idc_bc695 import *
```

3. refactor: removed the adapter idaapi.read_selection. idaapi.read_selection has been adapted internally
ida_kernwin.py
image

### CODE REVIEW

**Comment by fjh658** [comment]
tested ida6.8, ida6.9, ida6.95, ida7.0_b2, ida7.0_b3, ida7.0_b4, ida7.0_b5_x86, ida7.0_b5_x64, ida7.0_b6_x86, ida7.0_b6_x64,

**Comment by aquynh** [comment]
this looks good to me.

@Rupan, this reverts some code from your last PR. can you please confirm you dont have any issues with this PR now?

**Comment by fjh658** [comment]
@aquynh 
Yes. I have tested ida6.8, ida6.9, ida6.95, ida7.0_b2, ida7.0_b3, ida7.0_b4, ida7.0_b5_x86, ida7.0_b5_x64, ida7.0_b6_x86, ida7.0_b6_x64.

Question1. Since the ida7.0_b5 version, split out two versions of x86, x64. X64 is the main refactored version of hexray, x86 is partially modified on the basis of 6.95, idapython  procName does not change, so can not be compared by version. It will crash.
```python
try:
     cpuname = info.procname.lower()
except:
     cpuname = info.procName.lower()
```

not
```python
if idaapi.IDA_SDK_VERSION >= 700:
     cpuname = info.procname.lower()
else:
     cpuname = info.procName.lower()
```
Question2, 3. ida has been adapted  by hexray internally.

**Comment by aquynh** [comment]
yes, you handled Q1 in a better approach.

**Comment by fjh658** [comment]
@aquynh 
Q2, 3 is the same type of problem.

In the ida 7 for x64 python done refactoring operation, in order to be compatible with 695, in the configuration file python.cfg added
// shoulder the plugin automatically load a backward-compatibility-provide
// 'idaapi' wrapper module?
AUTOIMPORT_COMPAT_IDAAPI = YES

// Should the plugin automatically load a 6.95 bw-compatibility layer?
AUTOIMPORT_COMPAT_IDA695 = YES

and the default value is yes

```python
# init.py
try:
    import ida_idaapi
    import ida_kernwin  #importance
    import ida_diskio
except ImportError as e:
    print "Import failed: %s. Current sys.path:" % str(e)
    for p in sys.path:
        print "\t%s" % p
    raise
```

ida_kernwin.py
```python

import ida_idaapi
import sys
_BC695 = sys.modules["__main__"].IDAPYTHON_COMPAT_695_API  #importance
# ...
if _BC695:
    AST_DISABLE_FOR_FORM=AST_DISABLE_FOR_WIDGET
    AST_ENABLE_FOR_FORM=AST_ENABLE_FOR_WIDGET
    CB_CLOSE_IDB=CB_INVISIBLE
    chtype_generic2=chtype_generic
    chtype_segreg=chtype_srcp
    close_tform=close_widget
    find_tform=find_widget
    get_current_tform=get_current_widget
    get_highlighted_identifier=get_highlight
    get_tform_title=get_widget_title
    get_tform_type=get_widget_type
    is_chooser_tform=is_chooser_widget
    open_tform=display_widget
    pyscv_get_tcustom_control=pyscv_get_widget
    pyscv_get_tform=pyscv_get_widget
    __read_selection70 = read_selection
    def read_selection(*args):  #importance
        if len(args) == 0:
            # bw-compat
            t0, t1, view = twinpos_t(), twinpos_t(), get_current_viewer()
            sel = __read_selection70(view, t0, t1)
            import ida_idaapi
            a0, a1 = ida_idaapi.BADADDR, ida_idaapi.BADADDR
            if sel:
                a0, a1 = t0.place(view).toea(), t1.place(view).toea()
            return sel, a0, a1
        else:
            return __read_selection70(*args)
    readsel2=read_selection
```

The value of IDAPYTHON_COMPAT_695_API is determined by AUTOIMPORT_COMPAT_IDA695 = YES

Similarly, we can see

```python
# idc.py
# Compatibility macros (auto-generated part. Comes first so
# that any re-definition below will override auto-generated part)
if sys.modules["__main__"].IDAPYTHON_COMPAT_695_API: # importance
    # ...
    from idc_bc695 import *
```

**Comment by Rupan** [comment]
Indeed the code in this PR appears to be fine.  I just have a couple of suggestions regarding code style.  In my initial pull request I was going for the minimal amount changes required to resolve errors I saw in the code.

I've been playing around with a more thorough cleanup, but the code churn is significant and I want to be sure that I haven't introduced bugs in the process.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
