### PR TITLE
IDA 7.0 Beta checks and fixes

### PR DESCRIPTION
**Pull request by fdivrp**
# Changes
* IDA 7 check and use new read_selection
* IDA 7 add_menu_item removed and added version check and attach_action_to_menu
* Add display always for exception in the registered actions
* IDA 7 check and use all lowecase for this API info.procname.lower() 

* IDA 7 check and use finish_populating_widget_popup and get_widget_type for the right click hook

### CODE REVIEW

**Comment by aquynh** [comment]
looks great! do you want to merge this now, or only when right click fix is available?

**Comment by fdivrp** [comment]
It looked like the right click should work the same according to the SDK.  I'm not sure why it isn't working. Any ideas?

image

```
attach_action_to_popup(tcc, popup_handle, name, popuppath=None, flags=0)
attach_action_to_popup(form, popup_handle, name, popuppath=None, flags=0) -> bool
```

**Comment by aquynh** [comment]
can we forward this question to Hexray, to see what they have to say?

**Comment by fdivrp** [comment]
Yep, I did. We will see what they say if it's a bug or something else major changed.

**Comment by fdivrp** [comment]
I made the recommended changes from Arnaud and the right click hook works now.

`
# hooks for popup menu
class Hooks(idaapi.UI_Hooks):
    if idaapi.IDA_SDK_VERSION >= 700:
        # IDA >= 700 right click widget popup
        def finish_populating_widget_popup(self, form, popup):
            if idaapi.get_widget_type(form) == idaapi.BWN_DISASM:
                try:
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Patcher.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Fill_Range.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Undo.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, "-", 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Search.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, "-", 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Updater.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_About.get_name(), 'Keypatch/')
                except:
                    pass
    else:
        # IDA < 700 right click popup
        def finish_populating_tform_popup(self, form, popup):
            # We'll add our action to all "IDA View-*"s.
            # If we wanted to add it only to "IDA View-A", we could
            # also discriminate on the widget's title:
            #
            #  if idaapi.get_tform_title(form) == "IDA View-A":
            #      ...
            #
            if idaapi.get_tform_type(form) == idaapi.BWN_DISASM:
                try:
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Patcher.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Fill_Range.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Undo.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, "-", 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Search.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, "-", 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_Updater.get_name(), 'Keypatch/')
                    idaapi.attach_action_to_popup(form, popup, Kp_MC_About.get_name(), 'Keypatch/')
                except:
                    pass
`

**Comment by aquynh** [comment]
merged, thanks for this amazing work!

i updated https://github.com/keystone-engine/keypatch/blob/master/CREDITS.TXT with your name added.

**Pull request merged**
