### PR TITLE
Add install methods for IDA 7.0 windows

### PR DESCRIPTION
**Pull request by SilverBut**
Also left space for other OS.

It also can be merged together with pr #30

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by enovella** [comment]
Hey can you add more details regarding PATH, versions and so on?

**Comment by SilverBut** [comment]
@enovella 
1. As for the `PATH`. Since sometimes the Python installed by IDA installer is NOT added into the `PATH`, which means, you can not type in `python` in `cmd` to open a python console, you need to add those vars into your `PATH`. This is just to get the right binary of `pip` and `python` working. You may want to check [this guide from Python's doc](https://docs.python.org/2/using/windows.html) for more info. As for other things about PATH and versions....I did not met such problems, and please tell me if you have any.
2. "Be sure you are installing 64-bit version" means what you need to install is an 64-bit keystone. Since both IDA, OS and Python are 64-bit ones, you need to use a 64-bit keystone to keep them compatible.

Just let me know if this reply solved your problem, and I will open another pull request if needed ;)

**Comment by enovella** [comment]
Hi @SilverBut,

Thanks a lot for your explanation. 

I installed both python2 `win32` & `amd64` in my machine and add them to my `PATH`. However, when trying to install `keystone-engine` through pip, I got an error regarding `keystone.so`, which is a bug because I'm in a windows environment and should be `keystone.dll`. I have seen similar error and patched the `setup.py` installer. Nevertheless, I got the same error when firing up IDA with ImportError of Keystone.

It seems that the windows pip package is kinda broken. Isnt it?

**Comment by SilverBut** [comment]
@enovella 
Seems there do have a bug according to your log. However I can not reproduce it on neither of my VMs.
Have you ever tried using `keystone` from the installer on the [homepage](http://www.keystone-engine.org/download/) instead of using `pip`?

**Pull request merged**
