### PR TITLE
Fixed the form cannot be shown for ida pro 7.2 release version

### PR DESCRIPTION
**Pull request by fjh658**
Fixed the form(Patcher, Search, Fill Range) cannot be shown for ida pro 7.2 release version. 
- `The PR has been tested on ida6.x, ida7.0, 7.1, 7.2.` @aquynh

Please see the picture below:
image

### CODE REVIEW

**Comment by fjh658** [comment]
Please review  PR. @aquynh Thank you.

**Comment by aquynh** [comment]
sorry for very late reply!

this looks good, but please confirm that this works for v6.x

**Comment by aquynh** [comment]
also, would you mind verifying the pull req https://github.com/keystone-engine/keypatch/pull/36, to confirm it works for v7.x?

thanks!

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
